CREATE TABLE CITIES
(
    ID   INT4 PRIMARY KEY ,
    CODE VARCHAR(4),
    NAME VARCHAR(256)
);
CREATE TABLE PARKING_FACILITIES
(
    TYPE               VARCHAR(31)  NOT NULL,
    ID                 VARCHAR(255) PRIMARY KEY ,
    AVAILABLE_CAPACITY INT4,
    CAPACITY           INT4,
    NAME               VARCHAR(256),
    CITY_ID            INT4 references CITIES
);
CREATE TABLE CITIES_PARKING_FACILITIES
(
    CITY_ID               INT4         NOT NULL references CITIES,
    PARKING_FACILITIES_ID VARCHAR(255) NOT NULL UNIQUE references PARKING_FACILITIES
);

CREATE TABLE VEHICLES
(
    TYPE                VARCHAR(31)  NOT NULL,
    ID                  VARCHAR(255) PRIMARY KEY,
    IS_PARKED           BOOLEAN,
    CITY_ID             INT4 references CITIES,
    PARKING_FACILITY_ID VARCHAR(255) references PARKING_FACILITIES
);